// AUTO-GENERATED from BombSquad APK
// Textures: 431 | Sounds: 432 | Meshes: 295
// The site reads from Textures/ and Sounds/ folders at runtime;
// this list is a fallback used when folder-read fails (e.g. local file://).

const BS_DATA = {
  textures: [
    'achievementBoxer', 'achievementCrossHair', 'achievementDualWielding', 'achievementEmpty', 'achievementFlawlessVictory',
    'achievementFootballShutout', 'achievementFootballVictory', 'achievementFreeLoader', 'achievementGotTheMoves', 'achievementInControl',
    'achievementMedalLarge', 'achievementMedalMedium', 'achievementMedalSmall', 'achievementMine', 'achievementOffYouGo',
    'achievementOnslaught', 'achievementOutline', 'achievementRunaround', 'achievementSharingIsCaring', 'achievementStayinAlive',
    'achievementSuperPunch', 'achievementTNT', 'achievementTeamPlayer', 'achievementWall', 'achievementsIcon',
    'actionButtons', 'actionHeroColor', 'actionHeroColorMask', 'actionHeroIcon', 'actionHeroIconColorMask',
    'advancedIcon', 'agentColor', 'agentColorMask', 'agentIcon', 'agentIconColorMask',
    'aliColor', 'aliColorMask', 'aliIcon', 'aliIconColorMask', 'aliSplash',
    'alienColor', 'alienColorMask', 'alienIcon', 'alienIconColorMask', 'alwaysLandBGColor',
    'alwaysLandLevelColor', 'alwaysLandPreview', 'analogStick', 'arrow', 'assassinColor',
    'assassinColorMask', 'assassinIcon', 'assassinIconColorMask', 'audioIcon', 'backIcon',
    'bar', 'bearColor', 'bearColorMask', 'bearIcon', 'bearIconColorMask',
    'bg', 'bigG', 'bigGPreview', 'black', 'bombButton',
    'bombColor', 'bombColorIce', 'bombStickyColor', 'bonesColor', 'bonesColorMask',
    'bonesIcon', 'bonesIconColorMask', 'boxingGlovesColor', 'bridgitLevelColor', 'bridgitPreview',
    'bunnyColor', 'bunnyColorMask', 'bunnyIcon', 'bunnyIconColorMask', 'buttonBomb',
    'buttonJump', 'buttonPickUp', 'buttonPunch', 'buttonSquare', 'buttonSquareWide',
    'chTitleChar1', 'chTitleChar2', 'chTitleChar3', 'chTitleChar4', 'chTitleChar5',
    'characterIconMask', 'chestIcon', 'chestIconEmpty', 'chestIconMulti', 'chestIconTint',
    'chestOpenIcon', 'chestOpenIconTint', 'circle', 'circleNoAlpha', 'circleOutline',
    'circleOutlineNoAlpha', 'circleShadow', 'circleSoft', 'circleZigZag', 'clayStroke',
    'coin', 'controllerIcon', 'courtyardLevelColor', 'courtyardPreview', 'cowboyColor',
    'cowboyColorMask', 'cowboyIcon', 'cowboyIconColorMask', 'cragCastleLevelColor', 'cragCastlePreview',
    'crossOut', 'crossOutMask', 'cursor', 'cuteSpaz', 'cyborgColor',
    'cyborgColorMask', 'cyborgIcon', 'cyborgIconColorMask', 'discordIcon', 'discordLogo',
    'discordServer', 'doomShroomBGColor', 'doomShroomLevelColor', 'doomShroomPreview', 'downButton',
    'egg1', 'egg2', 'egg3', 'egg4', 'eggTex1',
    'eggTex2', 'eggTex3', 'empty', 'explosion', 'eyeColor',
    'eyeColorTintMask', 'file', 'flagColor', 'flagPoleColor', 'folder',
    'fontBig', 'fontExtras', 'fontExtras2', 'fontExtras3', 'fontExtras4',
    'fontExtras5', 'fontSmall0', 'fontSmall1', 'fontSmall2', 'fontSmall3',
    'fontSmall4', 'fontSmall5', 'fontSmall6', 'fontSmall7', 'footballStadium',
    'footballStadiumPreview', 'frameInset', 'frostyColor', 'frostyColorMask', 'frostyIcon',
    'frostyIconColorMask', 'fuse', 'gameCenterIcon', 'githubLogo', 'gladiatorColor',
    'gladiatorColorMask', 'gladiatorIcon', 'gladiatorIconColorMask', 'glow', 'goldPass',
    'googlePlayAchievementsIcon', 'googlePlayGamesIcon', 'googlePlayLeaderboardsIcon', 'googlePlusIcon', 'googlePlusSignInButton',
    'graphicsIcon', 'heart', 'hockeyStadium', 'hockeyStadiumPreview', 'iconOnslaught',
    'iconRunaround', 'impactBombColor', 'impactBombColorLit', 'inventoryIcon', 'jackColor',
    'jackColorMask', 'jackIcon', 'jackIconColorMask', 'jumpsuitColor', 'jumpsuitColorMask',
    'jumpsuitIcon', 'jumpsuitIconColorMask', 'kronk', 'kronkColorMask', 'kronkIcon',
    'kronkIconColorMask', 'lakeFrigid', 'lakeFrigidPreview', 'lakeFrigidReflections', 'landMine',
    'landMineLit', 'leaderboardsIcon', 'leftButton', 'levelIcon', 'light',
    'lightSharp', 'lightSoft', 'lock', 'logIcon', 'logo',
    'logoEaster', 'mapPreviewMask', 'medalBronze', 'medalComplete', 'medalGold',
    'medalSilver', 'melColor', 'melColorMask', 'melIcon', 'melIconColorMask',
    'menuBG', 'menuButton', 'menuIcon', 'merch', 'meter',
    'monkeyFaceLevelColor', 'monkeyFacePreview', 'multiplayerExamples', 'natureBackgroundColor', 'neoSpazColor',
    'neoSpazColorMask', 'neoSpazIcon', 'neoSpazIconColorMask', 'nextLevelIcon', 'ninjaColor',
    'ninjaColorMask', 'ninjaIcon', 'ninjaIconColorMask', 'nub', 'null',
    'oldLadyColor', 'oldLadyColorMask', 'oldLadyIcon', 'oldLadyIconColorMask', 'operaSingerColor',
    'operaSingerColorMask', 'operaSingerIcon', 'operaSingerIconColorMask', 'ouyaAButton', 'ouyaIcon',
    'ouyaOButton', 'ouyaUButton', 'ouyaYButton', 'pageLeftRight', 'penguinColor',
    'penguinColorMask', 'penguinIcon', 'penguinIconColorMask', 'pixieColor', 'pixieColorMask',
    'pixieIcon', 'pixieIconColorMask', 'playerLineup', 'plusButton', 'powerupBomb',
    'powerupCurse', 'powerupHealth', 'powerupIceBombs', 'powerupImpactBombs', 'powerupLandMines',
    'powerupPunch', 'powerupShield', 'powerupSpeed', 'powerupStickyBombs', 'puckColor',
    'quoteBubble', 'rampageBGColor', 'rampageBGColor2', 'rampageLevelColor', 'rampagePreview',
    'reflectionChar_+x', 'reflectionChar_+y', 'reflectionChar_+z', 'reflectionChar_-x', 'reflectionChar_-y',
    'reflectionChar_-z', 'reflectionPowerup_+x', 'reflectionPowerup_+y', 'reflectionPowerup_+z', 'reflectionPowerup_-x',
    'reflectionPowerup_-y', 'reflectionPowerup_-z', 'reflectionSharp_+x', 'reflectionSharp_+y', 'reflectionSharp_+z',
    'reflectionSharp_-x', 'reflectionSharp_-y', 'reflectionSharp_-z', 'reflectionSharper_+x', 'reflectionSharper_+y',
    'reflectionSharper_+z', 'reflectionSharper_-x', 'reflectionSharper_-y', 'reflectionSharper_-z', 'reflectionSharpest_+x',
    'reflectionSharpest_+y', 'reflectionSharpest_+z', 'reflectionSharpest_-x', 'reflectionSharpest_-y', 'reflectionSharpest_-z',
    'reflectionSoft_+x', 'reflectionSoft_+y', 'reflectionSoft_+z', 'reflectionSoft_-x', 'reflectionSoft_-y',
    'reflectionSoft_-z', 'replayIcon', 'rgbStripes', 'rightButton', 'robotColor',
    'robotColorMask', 'robotIcon', 'robotIconColorMask', 'roundaboutLevelColor', 'roundaboutPreview',
    'santaColor', 'santaColorMask', 'santaIcon', 'santaIconColorMask', 'scorch',
    'scorchBig', 'scrollWidget', 'scrollWidgetGlow', 'settingsIcon', 'shadow',
    'shadowSharp', 'shadowSoft', 'shield', 'shrapnel1Color', 'slash',
    'smoke', 'softRect', 'softRect2', 'softRectVertical', 'sparks',
    'spinner', 'spinner0', 'spinner1', 'spinner10', 'spinner11',
    'spinner2', 'spinner3', 'spinner4', 'spinner5', 'spinner6',
    'spinner7', 'spinner8', 'spinner9', 'star', 'startButton',
    'stepRightUpLevelColor', 'stepRightUpPreview', 'storeCharacter', 'storeCharacterEaster', 'storeCharacterXmas',
    'storeIcon', 'superheroColor', 'superheroColorMask', 'superheroIcon', 'superheroIconColorMask',
    'textClearButton', 'thePadLevelColor', 'thePadPreview', 'ticketRoll', 'ticketRollBig',
    'ticketRolls', 'tickets', 'ticketsMore', 'ticketsPurple', 'tipTopBGColor',
    'tipTopLevelColor', 'tipTopPreview', 'tnt', 'tokens1', 'tokens2',
    'tokens3', 'tokens4', 'touchArrows', 'touchArrowsActions', 'towerDLevelColor',
    'towerDPreview', 'treesColor', 'trophy', 'tv', 'uiAtlas',
    'uiAtlas2', 'upButton', 'usersButton', 'vrFillMound', 'warriorColor',
    'warriorColorMask', 'warriorIcon', 'warriorIconColorMask', 'white', 'windowBottomCap',
    'windowHSmallVMed', 'windowHSmallVSmall', 'wings', 'witchColor', 'witchColorMask',
    'witchIcon', 'witchIconColorMask', 'wizardColor', 'wizardColorMask', 'wizardIcon',
    'wizardIconColorMask', 'wrestlerColor', 'wrestlerColorMask', 'wrestlerIcon', 'wrestlerIconColorMask',
    'zigZagLevelColor', 'zigzagPreview', 'zoeColor', 'zoeColorMask', 'zoeIcon',
    'zoeIconColorMask'
  ],

  sounds: [
    'achievement', 'actionHero1', 'actionHero2', 'actionHero3', 'actionHero4',
    'actionHeroDeath', 'actionHeroFall', 'actionHeroHit1', 'actionHeroHit2', 'activateBeep',
    'agent1', 'agent2', 'agent3', 'agent4', 'agentDeath',
    'agentFall', 'agentHit1', 'agentHit2', 'alarm', 'ali1',
    'ali2', 'ali3', 'ali4', 'aliDeath', 'aliFall',
    'aliHit1', 'aliHit2', 'alien1', 'alien2', 'alien3',
    'alien4', 'alienDeath', 'alienFall', 'alienHit1', 'alienHit2',
    'announceEight', 'announceFive', 'announceFour', 'announceNine', 'announceOne',
    'announceSeven', 'announceSix', 'announceTen', 'announceThree', 'announceTwo',
    'assassin1', 'assassin2', 'assassin3', 'assassin4', 'assassinDeath',
    'assassinFall', 'assassinHit1', 'assassinHit2', 'aww', 'bear1',
    'bear2', 'bear3', 'bear4', 'bearDeath', 'bearFall',
    'bearHit1', 'bearHit2', 'bellHigh', 'bellLow', 'bellMed',
    'bigImpact', 'bigImpact2', 'blank', 'blip', 'block',
    'bombDrop01', 'bombDrop02', 'bombRoll01', 'bones1', 'bones2',
    'bones3', 'bonesDeath', 'bonesFall', 'boo', 'boxDrop',
    'boxingBell', 'bunny1', 'bunny2', 'bunny3', 'bunny4',
    'bunnyDeath', 'bunnyFall', 'bunnyHit1', 'bunnyHit2', 'bunnyJump',
    'cashRegister', 'cashRegister2', 'charSelectMusic', 'cheer', 'click01',
    'corkPop', 'corkPop2', 'cowboy1', 'cowboy2', 'cowboy3',
    'cowboy4', 'cowboyDeath', 'cowboyFall', 'cowboyHit1', 'cowboyHit2',
    'crowdChant', 'cyborg1', 'cyborg2', 'cyborg3', 'cyborg4',
    'cyborgDeath', 'cyborgFall', 'cyborgHit1', 'cyborgHit2', 'cymbal',
    'debrisFall', 'deek', 'deek2', 'ding', 'dingSmall',
    'dingSmallHigh', 'dripity', 'drumRoll', 'drumRollShort', 'error',
    'explosion01', 'explosion02', 'explosion03', 'explosion04', 'explosion05',
    'fanfare', 'flagCatcherMusic', 'flyingMusic', 'foghorn', 'footImpact01',
    'footImpact02', 'footImpact03', 'forwardMarchMusic', 'freeze', 'frosty01',
    'frosty02', 'frosty03', 'frosty04', 'frosty05', 'frostyDeath',
    'frostyFall', 'frostyHit01', 'frostyHit02', 'frostyHit03', 'fuse01',
    'gasp', 'gladiator1', 'gladiator2', 'gladiator3', 'gladiator4',
    'gladiatorDeath', 'gladiatorFall', 'gladiatorHit1', 'gladiatorHit2', 'gong',
    'grandRompMusic', 'gravelSkid', 'gunCocking', 'healthPowerup', 'hiss',
    'impactHard', 'impactHard2', 'impactHard3', 'impactMedium', 'impactMedium2',
    'jack01', 'jack02', 'jack03', 'jack04', 'jack05',
    'jack06', 'jackDeath01', 'jackFall01', 'jackHit01', 'jackHit02',
    'jackHit03', 'jackHit04', 'jackHit05', 'jackHit06', 'jackHit07',
    'jumpsuit1', 'jumpsuit2', 'jumpsuit3', 'jumpsuit4', 'jumpsuitDeath',
    'jumpsuitFall', 'jumpsuitHit1', 'jumpsuitHit2', 'kronk1', 'kronk10',
    'kronk2', 'kronk3', 'kronk4', 'kronk5', 'kronk6',
    'kronk7', 'kronk8', 'kronk9', 'kronkDeath', 'kronkFall',
    'laser', 'laserReverse', 'mel01', 'mel02', 'mel03',
    'mel04', 'mel05', 'mel06', 'mel07', 'mel08',
    'mel09', 'mel10', 'melDeath01', 'melFall01', 'menuMusic',
    'metalHit', 'metalSkid', 'nice', 'ninjaAttack1', 'ninjaAttack2',
    'ninjaAttack3', 'ninjaAttack4', 'ninjaAttack5', 'ninjaAttack6', 'ninjaAttack7',
    'ninjaDeath1', 'ninjaFall1', 'ninjaHit1', 'ninjaHit2', 'ninjaHit3',
    'ninjaHit4', 'ninjaHit5', 'ninjaHit6', 'ninjaHit7', 'ninjaHit8',
    'oldLady1', 'oldLady2', 'oldLady3', 'oldLady4', 'oldLadyDeath',
    'oldLadyFall', 'oldLadyHit1', 'oldLadyHit2', 'ooh', 'operaSinger1',
    'operaSinger2', 'operaSinger3', 'operaSinger4', 'operaSingerDeath', 'operaSingerFall',
    'operaSingerHit1', 'operaSingerHit2', 'orchestraHit', 'orchestraHit2', 'orchestraHit3',
    'orchestraHit4', 'orchestraHitBig1', 'orchestraHitBig2', 'penguin1', 'penguin2',
    'penguin3', 'penguin4', 'penguinDeath', 'penguinFall', 'penguinHit1',
    'penguinHit2', 'pixie1', 'pixie2', 'pixie3', 'pixie4',
    'pixieDeath', 'pixieFall', 'pixieHit1', 'pixieHit2', 'playerDeath',
    'playerLeft', 'pop01', 'powerdown01', 'powerup01', 'punch01',
    'punchStrong01', 'punchStrong02', 'punchSwish', 'punchWeak01', 'raceBeep1',
    'raceBeep2', 'refWhistle', 'revUp', 'robot1', 'robot2',
    'robot3', 'robot4', 'robotDeath', 'robotFall', 'robotHit1',
    'robotHit2', 'runAwayMusic', 'santa01', 'santa02', 'santa03',
    'santa04', 'santa05', 'santaDeath', 'santaFall', 'santaHit01',
    'santaHit02', 'santaHit03', 'santaHit04', 'scamper01', 'scaryMusic',
    'score', 'scoreHit01', 'scoreHit02', 'scoreIncrease', 'scoresEpicMusic',
    'shatter', 'shieldDown', 'shieldHit', 'shieldUp', 'skid01',
    'slowEpicMusic', 'sparkle01', 'sparkle02', 'sparkle03', 'spawn',
    'spazAttack01', 'spazAttack02', 'spazAttack03', 'spazAttack04', 'spazDeath01',
    'spazEff', 'spazFall01', 'spazImpact01', 'spazImpact02', 'spazImpact03',
    'spazImpact04', 'spazJump01', 'spazJump02', 'spazJump03', 'spazJump04',
    'spazOw', 'spazPickup01', 'spazScream01', 'splatter', 'sportsMusic',
    'stickyImpact', 'superPunch', 'superhero1', 'superhero2', 'superhero3',
    'superhero4', 'superheroDeath', 'superheroFall', 'superheroHit1', 'superheroHit2',
    'survivalMusic', 'swip', 'swip2', 'swish', 'swish2',
    'swish3', 'tap', 'technoHit01', 'tick', 'ticking',
    'tickingCrazy', 'toTheDeathMusic', 'trashRummage', 'victoryMusic', 'warnBeep',
    'warnBeeps', 'warrior1', 'warrior2', 'warrior3', 'warrior4',
    'warriorDeath', 'warriorFall', 'warriorHit1', 'warriorHit2', 'whenJohnnyComesMarchingHomeMusic',
    'witch1', 'witch2', 'witch3', 'witch4', 'witchDeath',
    'witchFall', 'witchHit1', 'witchHit2', 'wizard1', 'wizard2',
    'wizard3', 'wizard4', 'wizardDeath', 'wizardFall', 'wizardHit1',
    'wizardHit2', 'woo', 'woo2', 'woo3', 'woodDebrisFall',
    'wow', 'wrestler1', 'wrestler2', 'wrestler3', 'wrestler4',
    'wrestlerDeath', 'wrestlerFall', 'wrestlerHit1', 'wrestlerHit2', 'yeah',
    'zoeAttack01', 'zoeAttack02', 'zoeAttack03', 'zoeAttack04', 'zoeDeath01',
    'zoeEff', 'zoeFall01', 'zoeImpact01', 'zoeImpact02', 'zoeImpact03',
    'zoeImpact04', 'zoeJump01', 'zoeJump02', 'zoeJump03', 'zoeOw',
    'zoePickup01', 'zoeScream01'
  ],

  meshes: [
    'actionButtonBottom', 'actionButtonLeft', 'actionButtonRight', 'actionButtonTop', 'actionHeroForeArm',
    'actionHeroHand', 'actionHeroHead', 'actionHeroLowerLeg', 'actionHeroPelvis', 'actionHeroToes',
    'actionHeroTorso', 'actionHeroUpperArm', 'actionHeroUpperLeg', 'agentForeArm', 'agentHand',
    'agentHead', 'agentLowerLeg', 'agentPelvis', 'agentToes', 'agentTorso',
    'agentUpperArm', 'agentUpperLeg', 'aliForeArm', 'aliHand', 'aliHead',
    'aliLowerLeg', 'aliPelvis', 'aliToes', 'aliTorso', 'aliUpperArm',
    'aliUpperLeg', 'alienForeArm', 'alienHand', 'alienHead', 'alienLowerLeg',
    'alienPelvis', 'alienToes', 'alienTorso', 'alienUpperArm', 'alienUpperLeg',
    'assassinForeArm', 'assassinHand', 'assassinHead', 'assassinLowerLeg', 'assassinPelvis',
    'assassinToes', 'assassinTorso', 'assassinUpperArm', 'assassinUpperLeg', 'bearForeArm',
    'bearHand', 'bearHead', 'bearLowerLeg', 'bearPelvis', 'bearToes',
    'bearTorso', 'bearUpperArm', 'bearUpperLeg', 'bomb', 'bombSticky',
    'bonesForeArm', 'bonesHand', 'bonesHead', 'bonesLowerLeg', 'bonesPelvis',
    'bonesToes', 'bonesTorso', 'bonesUpperArm', 'bonesUpperLeg', 'box',
    'boxingGlove', 'bunnyForeArm', 'bunnyHand', 'bunnyHead', 'bunnyLowerLeg',
    'bunnyPelvis', 'bunnyToes', 'bunnyTorso', 'bunnyUpperArm', 'bunnyUpperLeg',
    'cowboyForeArm', 'cowboyHand', 'cowboyHead', 'cowboyLowerLeg', 'cowboyPelvis',
    'cowboyToes', 'cowboyTorso', 'cowboyUpperArm', 'cowboyUpperLeg', 'cyborgForeArm',
    'cyborgHand', 'cyborgHead', 'cyborgLowerLeg', 'cyborgPelvis', 'cyborgToes',
    'cyborgTorso', 'cyborgUpperArm', 'cyborgUpperLeg', 'cylinder', 'egg',
    'frostyForeArm', 'frostyHand', 'frostyHead', 'frostyLowerLeg', 'frostyPelvis',
    'frostyToes', 'frostyTorso', 'frostyUpperArm', 'frostyUpperLeg', 'gladiatorForeArm',
    'gladiatorHand', 'gladiatorHead', 'gladiatorLowerLeg', 'gladiatorPelvis', 'gladiatorToes',
    'gladiatorTorso', 'gladiatorUpperArm', 'gladiatorUpperLeg', 'hairTuft1', 'hairTuft1b',
    'hairTuft2', 'hairTuft3', 'hairTuft4', 'impactBomb', 'jackForeArm',
    'jackHand', 'jackHead', 'jackLowerLeg', 'jackToes', 'jackTorso',
    'jackUpperArm', 'jackUpperLeg', 'jumpsuitForeArm', 'jumpsuitHand', 'jumpsuitHead',
    'jumpsuitLowerLeg', 'jumpsuitPelvis', 'jumpsuitToes', 'jumpsuitTorso', 'jumpsuitUpperArm',
    'jumpsuitUpperLeg', 'kronkForeArm', 'kronkHand', 'kronkHead', 'kronkLowerLeg',
    'kronkPelvis', 'kronkToes', 'kronkTorso', 'kronkUpperArm', 'kronkUpperLeg',
    'landMine', 'melForeArm', 'melHand', 'melHead', 'melLowerLeg',
    'melToes', 'melTorso', 'melUpperArm', 'melUpperLeg', 'neoSpazForeArm',
    'neoSpazHand', 'neoSpazHead', 'neoSpazLowerLeg', 'neoSpazPelvis', 'neoSpazToes',
    'neoSpazTorso', 'neoSpazUpperArm', 'neoSpazUpperLeg', 'ninjaForeArm', 'ninjaHand',
    'ninjaHead', 'ninjaLowerLeg', 'ninjaPelvis', 'ninjaToes', 'ninjaTorso',
    'ninjaUpperArm', 'ninjaUpperLeg', 'oldLadyForeArm', 'oldLadyHand', 'oldLadyHead',
    'oldLadyLowerLeg', 'oldLadyPelvis', 'oldLadyToes', 'oldLadyTorso', 'oldLadyUpperArm',
    'oldLadyUpperLeg', 'operaSingerForeArm', 'operaSingerHand', 'operaSingerHead', 'operaSingerLowerLeg',
    'operaSingerPelvis', 'operaSingerToes', 'operaSingerTorso', 'operaSingerUpperArm', 'operaSingerUpperLeg',
    'penguinForeArm', 'penguinHand', 'penguinHead', 'penguinLowerLeg', 'penguinPelvis',
    'penguinToes', 'penguinTorso', 'penguinUpperArm', 'penguinUpperLeg', 'pixieForeArm',
    'pixieHand', 'pixieHead', 'pixieLowerLeg', 'pixiePelvis', 'pixieToes',
    'pixieTorso', 'pixieUpperArm', 'pixieUpperLeg', 'plasticEyesTransparent', 'powerup',
    'powerupSimple', 'puck', 'robotForeArm', 'robotHand', 'robotHead',
    'robotLowerLeg', 'robotPelvis', 'robotToes', 'robotTorso', 'robotUpperArm',
    'robotUpperLeg', 'runningShoes', 'santaForeArm', 'santaHand', 'santaHead',
    'santaLowerLeg', 'santaToes', 'santaTorso', 'santaUpperArm', 'santaUpperLeg',
    'shield', 'shrapnel1', 'shrapnelBoard', 'shrapnelSlime', 'superheroForeArm',
    'superheroHand', 'superheroHead', 'superheroLowerLeg', 'superheroPelvis', 'superheroToes',
    'superheroTorso', 'superheroUpperArm', 'superheroUpperLeg', 'tnt', 'warriorForeArm',
    'warriorHand', 'warriorHead', 'warriorLowerLeg', 'warriorPelvis', 'warriorToes',
    'warriorTorso', 'warriorUpperArm', 'warriorUpperLeg', 'wing', 'witchForeArm',
    'witchHand', 'witchHead', 'witchLowerLeg', 'witchPelvis', 'witchToes',
    'witchTorso', 'witchUpperArm', 'witchUpperLeg', 'wizardForeArm', 'wizardHand',
    'wizardHead', 'wizardLowerLeg', 'wizardPelvis', 'wizardToes', 'wizardTorso',
    'wizardUpperArm', 'wizardUpperLeg', 'wrestlerForeArm', 'wrestlerHand', 'wrestlerHead',
    'wrestlerLowerLeg', 'wrestlerPelvis', 'wrestlerToes', 'wrestlerTorso', 'wrestlerUpperArm',
    'wrestlerUpperLeg', 'zoeForeArm', 'zoeHand', 'zoeHead', 'zoeLowerLeg',
    'zoePelvis', 'zoeToes', 'zoeTorso', 'zoeUpperArm', 'zoeUpperLeg'
  ],

  styles: ['spaz','female','ninja','kronk','mel','agent','ali','bear','bones','bunny','cyborg','frosty','penguin','pirate','pixie','santa'],

  characters: [
    { name: 'Spaz',          icon: 'neoSpazIcon',      style: 'spaz'    },
    { name: 'Zoe',           icon: 'zoeIcon',           style: 'female'  },
    { name: 'Snake Shadow',  icon: 'ninjaIcon',         style: 'ninja'   },
    { name: 'Kronk',         icon: 'kronkIcon',         style: 'kronk'   },
    { name: 'Mel',           icon: 'melIcon',           style: 'mel'     },
    { name: 'Jack Morgan',   icon: 'jackIcon',          style: 'pirate'  },
    { name: 'Frosty',        icon: 'frostyIcon',        style: 'frosty'  },
    { name: 'Bones',         icon: 'bonesIcon',         style: 'bones'   },
    { name: 'Bernard',       icon: 'bearIcon',          style: 'bear'    },
    { name: 'Pixel',         icon: 'pixieIcon',         style: 'pixie'   },
    { name: 'Pascal',        icon: 'penguinIcon',       style: 'penguin' },
    { name: 'Todd McBurton', icon: 'actionHeroIcon',    style: 'agent'   },
    { name: 'Agent Johnson', icon: 'agentIcon',         style: 'agent'   },
    { name: 'Lee',           icon: 'jumpsuitIcon',      style: 'ali'     },
    { name: 'Zola',          icon: 'assassinIcon',      style: 'ali'     },
    { name: 'Grumbledorf',   icon: 'wizardIcon',        style: 'spaz'    },
    { name: 'Butch',         icon: 'cowboyIcon',        style: 'spaz'    },
    { name: 'Witch',         icon: 'witchIcon',         style: 'female'  },
    { name: 'Warrior',       icon: 'warriorIcon',       style: 'spaz'    },
    { name: 'Middle-Man',    icon: 'superheroIcon',     style: 'agent'   },
    { name: 'Alien',         icon: 'alienIcon',         style: 'spaz'    },
    { name: 'OldLady',       icon: 'oldLadyIcon',       style: 'female'  },
    { name: 'Gladiator',     icon: 'gladiatorIcon',     style: 'spaz'    },
    { name: 'Wrestler',      icon: 'wrestlerIcon',      style: 'kronk'   },
    { name: 'Gretel',        icon: 'operaSingerIcon',   style: 'female'  },
    { name: 'Robot',         icon: 'robotIcon',         style: 'cyborg'  },
    { name: 'B-9000',        icon: 'cyborgIcon',        style: 'cyborg'  },
    { name: 'Easter Bunny',  icon: 'bunnyIcon',         style: 'bunny'   },
    { name: 'Santa Claus',   icon: 'santaIcon',         style: 'santa'   },
  ]
};
