const BS_DATA = {
  textures: [
    'actionHeroColor','actionHeroColorMask','actionHeroIcon','actionHeroIconColorMask',
    'agentColor','agentColorMask','agentIcon','agentIconColorMask',
    'aliColor','aliColorMask','aliIcon','aliIconColorMask',
    'alienColor','alienColorMask','alienIcon','alienIconColorMask',
    'assassinColor','assassinColorMask','assassinIcon','assassinIconColorMask',
    'bearColor','bearColorMask','bearIcon','bearIconColorMask',
    'bonesColor','bonesColorMask','bonesIcon','bonesIconColorMask',
    'bunnyColor','bunnyColorMask','bunnyIcon','bunnyIconColorMask',
    'cowboyColor','cowboyColorMask','cowboyIcon','cowboyIconColorMask',
    'cyborgColor','cyborgColorMask','cyborgIcon','cyborgIconColorMask',
    'frostyColor','frostyColorMask','frostyIcon','frostyIconColorMask',
    'gladiatorColor','gladiatorColorMask','gladiatorIcon','gladiatorIconColorMask',
    'jackColor','jackColorMask','jackIcon','jackIconColorMask',
    'jumpsuitColor','jumpsuitColorMask','jumpsuitIcon','jumpsuitIconColorMask',
    'kronk','kronkColorMask','kronkIcon','kronkIconColorMask',
    'melColor','melColorMask','melIcon','melIconColorMask',
    'neoSpazColor','neoSpazColorMask','neoSpazIcon','neoSpazIconColorMask',
    'ninjaColor','ninjaColorMask','ninjaIcon','ninjaIconColorMask',
    'oldLadyColor','oldLadyColorMask','oldLadyIcon','oldLadyIconColorMask',
    'operaSingerColor','operaSingerColorMask','operaSingerIcon','operaSingerIconColorMask',
    'penguinColor','penguinColorMask','penguinIcon','penguinIconColorMask',
    'pixieColor','pixieColorMask','pixieIcon','pixieIconColorMask',
    'robotColor','robotColorMask','robotIcon','robotIconColorMask',
    'santaColor','santaColorMask','santaIcon','santaIconColorMask',
    'superheroColor','superheroColorMask','superheroIcon','superheroIconColorMask',
    'warriorColor','warriorColorMask','warriorIcon','warriorIconColorMask',
    'witchColor','witchColorMask','witchIcon','witchIconColorMask',
    'wizardColor','wizardColorMask','wizardIcon','wizardIconColorMask',
    'wrestlerColor','wrestlerColorMask','wrestlerIcon','wrestlerIconColorMask',
    'zoeColor','zoeColorMask','zoeIcon','zoeIconColorMask',
    'bar','white','characterIconMask','circleZigZag',
    'discordServer','neoSpazColorMask'
  ],
  meshes: [
    'actionHeroHead','actionHeroTorso','actionHeroPelvis','actionHeroUpperArm','actionHeroForeArm','actionHeroHand','actionHeroUpperLeg','actionHeroLowerLeg','actionHeroToes',
    'agentHead','agentTorso','agentPelvis','agentUpperArm','agentForeArm','agentHand','agentUpperLeg','agentLowerLeg','agentToes',
    'aliHead','aliTorso','aliPelvis','aliUpperArm','aliForeArm','aliHand','aliUpperLeg','aliLowerLeg','aliToes',
    'alienHead','alienTorso','alienPelvis','alienUpperArm','alienForeArm','alienHand','alienUpperLeg','alienLowerLeg','alienToes',
    'assassinHead','assassinTorso','assassinPelvis','assassinUpperArm','assassinForeArm','assassinHand','assassinUpperLeg','assassinLowerLeg','assassinToes',
    'bearHead','bearTorso','bearPelvis','bearUpperArm','bearForeArm','bearHand','bearUpperLeg','bearLowerLeg','bearToes',
    'bonesHead','bonesTorso','bonesPelvis','bonesUpperArm','bonesForeArm','bonesHand','bonesUpperLeg','bonesLowerLeg','bonesToes', 'bomb',
    'bunnyHead','bunnyTorso','bunnyPelvis','bunnyUpperArm','bunnyForeArm','bunnyHand','bunnyUpperLeg','bunnyLowerLeg','bunnyToes',
    'cowboyHead','cowboyTorso','cowboyPelvis','cowboyUpperArm','cowboyForeArm','cowboyHand','cowboyUpperLeg','cowboyLowerLeg','cowboyToes',
    'cyborgHead','cyborgTorso','cyborgPelvis','cyborgUpperArm','cyborgForeArm','cyborgHand','cyborgUpperLeg','cyborgLowerLeg','cyborgToes',
    'frostyHead','frostyTorso','frostyPelvis','frostyUpperArm','frostyForeArm','frostyHand','frostyUpperLeg','frostyLowerLeg','frostyToes',
    'gladiatorHead','gladiatorTorso','gladiatorPelvis','gladiatorUpperArm','gladiatorForeArm','gladiatorHand','gladiatorUpperLeg','gladiatorLowerLeg','gladiatorToes',
    'jackHead','jackTorso','jackUpperArm','jackForeArm','jackHand','jackUpperLeg','jackLowerLeg','jackToes',
    'jumpsuitHead','jumpsuitTorso','jumpsuitPelvis','jumpsuitUpperArm','jumpsuitForeArm','jumpsuitHand','jumpsuitUpperLeg','jumpsuitLowerLeg','jumpsuitToes',
    'kronkHead','kronkTorso','kronkPelvis','kronkUpperArm','kronkForeArm','kronkHand','kronkUpperLeg','kronkLowerLeg','kronkToes',
    'melHead','melTorso','melUpperArm','melForeArm','melHand','melUpperLeg','melLowerLeg','melToes',
    'neoSpazHead','neoSpazTorso','neoSpazPelvis','neoSpazUpperArm','neoSpazForeArm','neoSpazHand','neoSpazUpperLeg','neoSpazLowerLeg','neoSpazToes',
    'ninjaHead','ninjaTorso','ninjaPelvis','ninjaUpperArm','ninjaForeArm','ninjaHand','ninjaUpperLeg','ninjaLowerLeg','ninjaToes',
    'oldLadyHead','oldLadyTorso','oldLadyPelvis','oldLadyUpperArm','oldLadyForeArm','oldLadyHand','oldLadyUpperLeg','oldLadyLowerLeg','oldLadyToes',
    'operaSingerHead','operaSingerTorso','operaSingerPelvis','operaSingerUpperArm','operaSingerForeArm','operaSingerHand','operaSingerUpperLeg','operaSingerLowerLeg','operaSingerToes',
    'penguinHead','penguinTorso','penguinPelvis','penguinUpperArm','penguinForeArm','penguinHand','penguinUpperLeg','penguinLowerLeg','penguinToes',
    'pixieHead','pixieTorso','pixiePelvis','pixieUpperArm','pixieForeArm','pixieHand','pixieUpperLeg','pixieLowerLeg','pixieToes',
    'robotHead','robotTorso','robotPelvis','robotUpperArm','robotForeArm','robotHand','robotUpperLeg','robotLowerLeg','robotToes',
    'santaHead','santaTorso','santaUpperArm','santaForeArm','santaHand','santaUpperLeg','santaLowerLeg','santaToes',
    'superheroHead','superheroTorso','superheroPelvis','superheroUpperArm','superheroForeArm','superheroHand','superheroUpperLeg','superheroLowerLeg','superheroToes',
    'warriorHead','warriorTorso','warriorPelvis','warriorUpperArm','warriorForeArm','warriorHand','warriorUpperLeg','warriorLowerLeg','warriorToes',
    'witchHead','witchTorso','witchPelvis','witchUpperArm','witchForeArm','witchHand','witchUpperLeg','witchLowerLeg','witchToes',
    'wizardHead','wizardTorso','wizardPelvis','wizardUpperArm','wizardForeArm','wizardHand','wizardUpperLeg','wizardLowerLeg','wizardToes',
    'wrestlerHead','wrestlerTorso','wrestlerPelvis','wrestlerUpperArm','wrestlerForeArm','wrestlerHand','wrestlerUpperLeg','wrestlerLowerLeg','wrestlerToes',
    'zoeHead','zoeTorso','zoePelvis','zoeUpperArm','zoeForeArm','zoeHand','zoeUpperLeg','zoeLowerLeg','zoeToes',
    'bomb','frostyPelvis','tnt'
  ],
  sounds: [
    'spazJump01','spazJump02','spazJump03','spazJump04',
    'spazAttack01','spazAttack02','spazAttack03','spazAttack04',
    'spazImpact01','spazImpact02','spazImpact03','spazImpact04',
    'spazDeath01','spazPickup01','spazFall01',
    'zoeJump01','zoeJump02','zoeJump03',
    'zoeAttack01','zoeAttack02','zoeAttack03','zoeAttack04',
    'zoeImpact01','zoeImpact02','zoeImpact03','zoeImpact04',
    'zoeDeath01','zoePickup01','zoeFall01',
    'ninjaAttack1','ninjaAttack2','ninjaAttack3','ninjaAttack4','ninjaAttack5','ninjaAttack6','ninjaAttack7',
    'ninjaHit1','ninjaHit2','ninjaHit3','ninjaHit4','ninjaHit5','ninjaHit6','ninjaHit7','ninjaHit8',
    'ninjaDeath1','ninjaFall1',
    'kronk1','kronk2','kronk3','kronk4','kronk5','kronk6','kronk7','kronk8','kronk9','kronk10',
    'kronkDeath','kronkFall',
    'mel01','mel02','mel03','mel04','mel05','mel06',
    'melDeath01','melFall01',
    'agentHit1','agentHit2','agentDeath','agentFall',
    'alienHit1','alienHit2','alienDeath','alienFall',
    'assassinHit1','assassinHit2','assassinDeath','assassinFall',
    'bearHit1','bearHit2','bearDeath','bearFall',
    'bonesDeath','bonesFall',
    'bunnyJump','bunnyHit1','bunnyHit2','bunnyDeath','bunnyFall',
    'cowboyHit1','cowboyHit2','cowboyDeath','cowboyFall',
    'cyborgHit1','cyborgHit2','cyborgDeath','cyborgFall',
    'frostyHit01','frostyHit02','frostyHit03','frostyDeath','frostyFall',
    'gladiatorHit1','gladiatorHit2','gladiatorDeath','gladiatorFall',
    'jackHit01','jackHit02','jackHit03','jackHit04','jackHit05','jackHit06','jackHit07',
    'jackDeath01','jackFall01',
    'jumpsuitHit1','jumpsuitHit2','jumpsuitDeath','jumpsuitFall',
    'oldLadyHit1','oldLadyHit2','oldLadyDeath','oldLadyFall',
    'operaSingerHit1','operaSingerHit2','operaSingerDeath','operaSingerFall',
    'penguinHit1','penguinHit2','penguinDeath','penguinFall',
    'pixieHit1','pixieHit2','pixieDeath','pixieFall',
    'robotHit1','robotHit2','robotDeath','robotFall',
    'santaHit01','santaHit02','santaHit03','santaHit04','santaDeath','santaFall',
    'superheroHit1','superheroHit2','superheroDeath','superheroFall',
    'warriorHit1','warriorHit2','warriorDeath','warriorFall',
    'witchHit1','witchHit2','witchDeath','witchFall',
    'wizardHit1','wizardHit2','wizardDeath','wizardFall',
    'wrestlerHit1','wrestlerHit2','wrestlerDeath','wrestlerFall',
    'aliHit1','aliHit2','aliDeath','aliFall',
    'actionHeroHit1','actionHeroHit2','actionHeroDeath','actionHeroFall',
    'zoePickup01','spazPickup01',
    'click01','deek','swip','error','cheer','foghorn','punch01','punchSwish','refWhistle'
  ],
  styles: ['spaz','female','ninja','kronk','mel','agent','ali','bear','bones','bunny','cyborg','frosty','penguin','pirate','pixie','santa'],
  characters: [
    { name: 'Spaz',          icon: 'neoSpazIcon',        style: 'spaz'    },
    { name: 'Zoe',           icon: 'zoeIcon',            style: 'female'  },
    { name: 'Snake Shadow',  icon: 'ninjaIcon',          style: 'ninja'   },
    { name: 'Kronk',         icon: 'kronkIcon',          style: 'kronk'   },
    { name: 'Mel',           icon: 'melIcon',            style: 'mel'     },
    { name: 'Jack Morgan',   icon: 'jackIcon',           style: 'pirate'  },
    { name: 'Frosty',        icon: 'frostyIcon',         style: 'frosty'  },
    { name: 'Bones',         icon: 'bonesIcon',          style: 'bones'   },
    { name: 'Bernard',       icon: 'bearIcon',           style: 'bear'    },
    { name: 'Pixel',         icon: 'pixieIcon',          style: 'pixie'   },
    { name: 'Pascal',        icon: 'penguinIcon',        style: 'penguin' },
    { name: 'Todd McBurton', icon: 'actionHeroIcon',     style: 'agent'   },
    { name: 'Agent Johnson', icon: 'agentIcon',          style: 'agent'   },
    { name: 'Lee',           icon: 'jumpsuitIcon',       style: 'ali'     },
    { name: 'Zola',          icon: 'assassinIcon',       style: 'ali'     },
    { name: 'Grumbledorf',   icon: 'wizardIcon',         style: 'spaz'    },
    { name: 'Butch',         icon: 'cowboyIcon',         style: 'spaz'    },
    { name: 'Witch',         icon: 'witchIcon',          style: 'female'  },
    { name: 'Warrior',       icon: 'warriorIcon',        style: 'spaz'    },
    { name: 'Middle-Man',    icon: 'superheroIcon',      style: 'agent'   },
    { name: 'Alien',         icon: 'alienIcon',          style: 'spaz'    },
    { name: 'OldLady',       icon: 'oldLadyIcon',        style: 'female'  },
    { name: 'Gladiator',     icon: 'gladiatorIcon',      style: 'spaz'    },
    { name: 'Wrestler',      icon: 'wrestlerIcon',       style: 'kronk'   },
    { name: 'Gretel',        icon: 'operaSingerIcon',    style: 'female'  },
    { name: 'Robot',         icon: 'robotIcon',          style: 'cyborg'  },
    { name: 'B-9000',        icon: 'cyborgIcon',         style: 'cyborg'  },
    { name: 'Easter Bunny',  icon: 'bunnyIcon',          style: 'bunny'   },
    { name: 'Santa Claus',   icon: 'santaIcon',          style: 'santa'   },
  ]
};
